---
# This is an example configuration manifest for omnibus-openstack. With this
# manifest you cen instruct omnibus-openstack which projects you would like
# to include, as well as provide specific versions/urls for the code. As yaml
# parsers can parse both yaml and json, this file may also be provided in a
# json format, if that suits your needs.

keystone:
  version: 'stable/havana'
  source:
    git: 'https://github.com/openstack/keystone.git'
glance:
  version: 'stable/havana'
  source:
    git: 'https://github.com/openstack/glance.git'
nova:
  version: 'stable/havana'
  source:
    git: 'https://github.com/openstack/nova.git'
cinder:
  version: 'stable/havana'
  source:
    git: 'https://github.com/openstack/cinder.git'
horizon:
  version: 'stable/havana'
  source:
    git: 'https://github.com/openstack/horizon.git'
neutron:
  version: 'stable/havana'
  source:
    git: 'https://github.com/openstack/neutron.git'


# These will all build the default 'master'
keystoneclient:
  source:
    git: 'https://github.com/openstack/python-keystoneclient.git'
glanceclient:
  source:
    git: 'https://github.com/openstack/python-glanceclient.git'
novaclient:
  source:
    git: 'https://github.com/openstack/python-novaclient.git'
cinderclient:
  source:
    git: 'https://github.com/openstack/python-cinderclient.git'
neutronclient:
  source:
    git: 'https://github.com/openstack/python-neutronclient.git'
